### ISSUE TITLE
Do not display closed amenities

### ISSUE THREAD

**Issue by terrylaire** [Rudloff/openvegemap#118]
Hi,

Thank you for this great application! I use it on Android. I've been updating OpenStreetMap with diets details and new places, but also with now closed places. I see that using the tags disused:* will not remove a place from OVM, or mark it closed.

I've read the code and thought at first that not displaying these places would be feasible and lighter in terms of exchanges with the API… Well it can be done. You can replace the overpass query with something like `nwr({{bbox}})[!"disused:shop"][!"disused:amenity"][~"^diet:.*$"~"."];out center;` I did not make a PR with it because I don't know if there is a loss in computing performances in the API with this more complex query, and I did not know if it was a welcome change, but here it is. What do you think of it ?

**Comment by Rudloff** [comment]
Hello, I guess this would make sense.
Feel free to submit a pull request :slightly_smiling_face: 
I am not sure about the impact on performances but we could test it.

**Comment by terrylaire** [comment]
Thank you, I did submit a PR!
