### ISSUE TITLE
Add a proportion detail

### ISSUE THREAD

**Issue by pichouk** [Rudloff/openvegemap#13]
my2cent feature idea : I think it can be interesting to add some details about the vegetarian/vegan proportions of dishes.
For example, for a specific diet you could mentioned :
- I don't know
- Yes (Mostly)
- Yes (Few dishes)
- No
- Only

Not sure if it is really needed, just saying.

**Comment by Rudloff** [comment]
The data comes from OpenStreetMap and [according to their wiki](https://wiki.openstreetmap.org/wiki/Key:diet), the only valid values are yes, no and only.

I agree it could be useful to have more information but I think it should be discussed with the OSM community first.

**Comment by pichouk** [comment]
Oh ok I didn't know data comes from OSM.
It seems that the subject is already discuss, so wait for it ;) => https://wiki.openstreetmap.org/wiki/Talk:Key:diet#Full_options_:_add_a_.22friendly.22_value

**Comment by pichouk** [comment]
No update from OSM on this feature since few month. Closing, will reopen if OSM change key available one day :)
