### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/openvegemap#20]

**Comment by hermann-san** [comment]
Could it make sense to you ntegrate OVM  into Happy cow website? they already have the means for writing reviews.

**Comment by Rudloff** [comment]
(This is off-topic on this issue but I will answer anyway.)

Happy Cow is a really useful website but AFAIK it is not open source.
However, we have plans to integrate https://lib.reviews/ in OVM: https://github.com/Rudloff/openvegemap-cordova/issues/7
