### ISSUE TITLE
Alternate info for people who can't see colors?

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/openvegemap#21]

**Comment by hiwelo** [comment]
Is it possible to provide different shapes for each kind of pins?
If not, you can use a pattern in the background for each kind of pins.

For example, Trello use a pattern system: 
<img width="300" alt="screen shot 2017-01-21 at 19 35 40" src="https://cloud.githubusercontent.com/assets/4989733/22176725/d3aa1890-e010-11e6-96f1-183f13f1d592.png">

**Comment by Rudloff** [comment]
The pattern seems to be a good idea! (And it could even solve the use case discussed in #23).
Unfortunately, [Leaflet.awesome-markers](https://github.com/lvoogdt/Leaflet.awesome-markers) doesn't allow us to do that, so it would require a bit more work.

**Comment by severoraz** [comment]
I have an idea: how about using a combination of shapes and border styles?
![image](https://cloud.githubusercontent.com/assets/13994462/22179074/399ccba6-e049-11e6-8ad7-cdb9b05d06ee.png)

**Comment by hiwelo** [comment]
Using different border styles to separate `yes` and `only` locations is a good idea.

In my opinion, the _background pattern_ is a more accessible idea than the _shape_ idea.

**Comment by severoraz** [comment]
Yes, I agree: it should look very consistent and affecting the inner icons should be prohibitive, perhaps rounding the borders of shapes could make them all more consistently sized whilst having all appropriate inner area for the establishment class icon. I like the pattern idea but I fear it may distract too much attention from the icon itself, and perhaps create some sort of zebra camouflage effect when several pins are next to each other in an overlap. What do you think?

**Comment by Rudloff** [comment]
I think we can use [Leaflet.extra-markers](https://github.com/coryasilva/Leaflet.ExtraMarkers).
It adds new shapes to awesome-markers:
![Leaflet.extra-markers screenshot](https://camo.githubusercontent.com/139673d887bedbf26e286ebfc5fb40d139f879f9/68747470733a2f2f7261772e6769746875622e636f6d2f636f72796173696c76612f4c6561666c65742e45787472614d61726b6572732f6d61737465722f73637265656e73686f742e706e67)

**Comment by Rudloff** [comment]
@hiwelo Do you think something like that could do?
![meat](https://cloud.githubusercontent.com/assets/840125/22183119/bae69b02-e0b6-11e6-9014-e48101c494e1.png) Meat
![vegetarian](https://cloud.githubusercontent.com/assets/840125/22183122/bb165298-e0b6-11e6-82ec-2664118ea13b.png) Vegetarian
![vegan](https://cloud.githubusercontent.com/assets/840125/22183120/bb158b7e-e0b6-11e6-8869-074e9eb06910.png) Vegan
![vegan-only](https://cloud.githubusercontent.com/assets/840125/22183121/bb1645e6-e0b6-11e6-94c1-9ec1a62283d7.png) Vegan only

**Comment by severoraz** [comment]
I think that works!

**Comment by Rudloff** [comment]
I'm starting to think that the current icons are not really useful (since the vast majority of the tagged locations are restaurants or coffee shops) and so we could use very simple icons like this:
![meat](https://cloud.githubusercontent.com/assets/840125/22187825/468c5862-e10d-11e6-9936-ed2c133d4bd8.png) Meat
![unknown](https://cloud.githubusercontent.com/assets/840125/22187826/46a91b0a-e10d-11e6-9eee-69c79417aefa.png) Unknown
![vegetarian](https://cloud.githubusercontent.com/assets/840125/22187827/46b09e84-e10d-11e6-893e-08fc65c04dde.png) Vegetarian
![vegan](https://cloud.githubusercontent.com/assets/840125/22187828/46b144ba-e10d-11e6-835b-19756d902635.png) Vegan
![vegan-only](https://cloud.githubusercontent.com/assets/840125/22187829/46b20148-e10d-11e6-828f-300256c19215.png) Vegan only

And if we don't want to loose the information about the type, we can move it to the tooltip:
![jeannette](https://cloud.githubusercontent.com/assets/840125/22187930/2c165102-e10f-11e6-86f6-959f4de4c26a.png)

**Comment by hiwelo** [comment]
@Rudloff I like this last idea with the emoji in the tooltip ✌️

**Comment by severoraz** [comment]
Well, that certainly looks good! Would it be possible though to include the establishment type as an icon on a corner of the marker? I know you said most places are restaurants anyway but if it could be done I think it would look good also

**Comment by Rudloff** [comment]
@severoraz We don't have an easy way to do this with Leaflet and I think it would make the map less readable because of too much information.
