### ISSUE TITLE
Missing OSM attibution on map

### ISSUE THREAD

**Issue by msevilla00** [Rudloff/openvegemap#22]
Hi,
I like your map but if you use OpenStreetMap data or rendered maps from there you have to show an attribution text. 
More info: http://wiki.osmfoundation.org/wiki/Licence 
or better: http://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#What_do_you_mean_by_.22Attribution.22.3F
Cheers

**Comment by Rudloff** [comment]
Hello,
The attribution is available in the _About_ menu item. Isn't that enough?

**Comment by msevilla00** [comment]
If you follow the instructions of OSM Wiki page that is not correct:
Read this: http://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#Where_to_put_it.3F

"How should I attribute you?
[...]
Where to put it?
[...]

For a browsable electronic map (e.g. embedded in a web page or mobile phone application), the credit should typically appear in the corner of the map, as commonly seen with map APIs/libraries such as Google Maps."

Even, I guess you should say who produce the tiles you use (they look like Wikimedia maps). There are hundreds of examples on internet to see how to do it.

I guess you could edit the code in leaflet and remove/change ".leaflet-control-attribution{display:none;}"

Cheers

**Comment by Rudloff** [comment]
OK, I don't really like Leaflet's attribution control, especially on mobile where it is really easy to misclick but I'll add it.
