### ISSUE TITLE
new color for diet:vegan=only

### ISSUE THREAD

**Issue by severoraz** [Rudloff/openvegemap#23]
I think places that are vegan only could sport a different color also, I think many would find that useful. On other maps people have suggested color blue, which I think is a fine suggestion

**Comment by Rudloff** [comment]
Hello,
I am curious about your use case here.
For me, the primary usage of the map is to see quickly were I can eat ; so it does not really matter if a place is vegan-friendly or vegan-only.

Also I'm reluctant to add too many colors to the map. Wouldn't having this information in the popup be enough?

**Comment by severoraz** [comment]
Hm, probably yes. The use case is for people who want to promote or lobby for vegan only establishments, as an economic form of activism.

**Comment by Rudloff** [comment]
I added this info to the popup for now.
Instead of a new color, we might also think about something more subtle like a small icon in the corner of the marker.

**Comment by severoraz** [comment]
wow, that was fast, thanks! And yes, I think any visual identifier would do :smiley: it could even be something more subtle like a border but also a small icon like a star would be awesome
