### ISSUE TITLE
OsmAnd

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#26]
FYI: https://github.com/osmandapp/Osmand/issues/3824

**Comment by Rudloff** [comment]
Hello,
I'm not sure what you want me to do here. OVM is only displaying info coming from OSM so OsmAnd can't get that same info from the OSM API.

**Comment by dimqua** [comment]
Is it not possible to edit OSM data using OVM?

**Comment by Rudloff** [comment]
Yes, with the [editor](https://editor.openvegemap.netlib.re/) but OVM does not store any data, the changes are sent directly to OSM.

**Comment by dimqua** [comment]
It's cool, thanks for clarifying.
