### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#27]
Can I use OVM when I'm offline? On Windows, GNU/Linux or Android.

**Comment by Rudloff** [comment]
Currently, only the map tiles are cached but not the markers.
I guess it would make sense to store the markers as well but I not to think about the best way to do this.

**Comment by Rudloff** [comment]
Let's see if this can be implemented upstream: https://github.com/GuillaumeAmat/leaflet-overpass-layer/issues/15
If not, I will try to add a caching mechanism in OVM directly.

**Comment by jkarlson** [comment]
To note, you can do this in osmand for current features: search->categories->cafe & restaurant -> sliders on the right -> select diet vegan etc. -> and show on the map on the left.

In general I would hope to be able to somehow utilize osmand data in the future, perhaps even get osmand plugin.

**Comment by Rudloff** [comment]
It looks like this could now be implemented: https://github.com/GuillaumeAmat/leaflet-overpass-layer/issues/15
