### ISSUE TITLE
Vegetarian only option

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#28]
I think it's a bit confusing that there aren't a "vegetarian only" markers. For example, Subway is marked as vegetarian cafe (through it serves meat too), as well as veg-only Indian places.

**Comment by Rudloff** [comment]
First, I don't want to add too many different markers, I think it would make the map less readable. And you can already get this info by clicking on the marker.

The other problem is that a "vegetarian only" marker could be confusing (it would not be immediately clear for users if it means "vegetarian and vegan only" or "vegetarian but not vegan").

**Comment by dimqua** [comment]
May be it's a correct description, since both places are vegetarian-only.

>it would make the map less readable

Filters can solve this problem. ;-)

**Comment by Rudloff** [comment]
> Filters can solve this problem. ;-)

Hum, maybe instead of a new marker type, we can add a "vegatarian/vegan only" filter that hides every place that serves meat?

**Comment by dimqua** [comment]
If it's possible, yes, it's a good idea!

**Comment by Rudloff** [comment]
This will be included in the next release.
