### ISSUE TITLE
Change the direction provider

### ISSUE THREAD

**Issue by airon90** [Rudloff/openvegemap#32]
Is it possible to have a setting to choose which provider to offer directions? By now you offer French version of Google Maps (```https://www.google.fr/maps/dir//DESTLAT,DESTLONG```). I'd like to have the possibility to choose between other router provider, such as GraphHopper (```https://graphhopper.com/maps/?point=&point=DESTLAT%2CDESTLONG&vehicle=foot```), OpenRouteService (```https://openrouteservice.org/directions?n1=DESTLAT&n2=DESTLONG&n3=14&a=null,null,DESTLAT,DESTLONG&b=2&c=0&g1=-1&g2=0&k2=km```) or custom one. Is it possible?
Thank you very much!

**Comment by airon90** [comment]
You can check the OSM wiki at the [Routing](https://wiki.openstreetmap.org/wiki/Routing) page ;)
If you don't want to choose you can also leave a blank space where to fulfill with a custom link (like I did in the first message)

**Comment by Rudloff** [comment]
I added a preference for it, it will be in the next release :)
