### ISSUE TITLE
Add app to F-Droid store

### ISSUE THREAD

**Issue by arbie65** [Rudloff/openvegemap#33]
It would be useful to get OpenVegeMap added to F-droid store so people who do not have access to google play store can also get app.

https://f-droid.org/wiki/page/Inclusion_Policy

**Comment by Rudloff** [comment]
Hello,
There is already an issue for that here: https://github.com/Rudloff/openvegemap-cordova/issues/1
I'm currently waiting for an answer from the F-Droid team.
