### ISSUE TITLE
Tags question

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#37]
Does OVM mark places tagged **diet:lacto_vegetarian** and **diet:ovo_vegetarian** as vegetarian (vegetarian-friendly) or it simply ignore them?

**Comment by Rudloff** [comment]
We ignore them because they are almost never used (only 29 Lacto-Vegetarian and 7 Ovo-Vegetarian in the whole OSM database).
We could add it if people start using them but for now it's not very useful.

**Comment by dimqua** [comment]
What about **diet:raw** and **diet:fruitarian**?

**Comment by Rudloff** [comment]
There is also very little of them (6 Fruitarian and 61 Raw).
Also the scope of this app is to provide info for vegetarian and vegan people.
Displaying other diets would probably make the interface more complicated. I might do it someday but it is not a priority.
