### ISSUE TITLE
Get directions on Google?!

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#38]
"Get directions" button open Google Maps page. Why not use MapQuest or other OSM-based service?

**Comment by Rudloff** [comment]
Since #32, you can choose another routing provider in the preferences.

**Comment by dimqua** [comment]
Thanks! But how can I use custom one?

**Comment by Rudloff** [comment]
You can put an URL in the custom field.
For MapQuest, it would be this: `https://www.mapquest.com/directions/to/near-{LAT},{LON}`
