### ISSUE TITLE
Health food shops

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#39]
Please consider to add [shop=health_food tag](https://wiki.openstreetmap.org/wiki/Tag:shop=health_food) support to the map. There are also related tags such as **shop=nutrition_supplements**, **shop=herbalist**, **shop=organic**, and **shop=farm**.

**Comment by Rudloff** [comment]
These nodes are already displayed. Here is an example: https://openvegemap.netlib.re/#zoom=18&lat=47.7247215&lon=12.8794752
We display any node that has a `diet:` tag, regardless of its type.

**Comment by dimqua** [comment]
@Rudloff Good to know! Then it's probably a good idea to group any nodes that have a `shop:` tag as VegeShops or something like this.

**Comment by Rudloff** [comment]
I added a small explanation in the README: https://github.com/Rudloff/openvegemap/commit/89a306e55eccd171c6a63e5b01fde34678682221
