### ISSUE TITLE
logo for u 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [Rudloff/openvegemap#41]
Hello ,@Rudloff I want contribute toopenvegemap  so i designed a new logo for openvegemap and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my designed

**Comment by Rudloff** [comment]
Hello,
Thanks but I don't see any logo. Did you forget to attach it to the issue?

**Comment by Rudloff** [comment]
No answer so I'm closing.
