### ISSUE TITLE
Cafe Node cannot be added

### ISSUE THREAD

**Issue by loi219** [Rudloff/openvegemap#42]
Hi!
A Node is tagged has a cafe but it's a restaurant too, and I can't find it your app for adding it: [Node](https://www.openstreetmap.org/relation/1680045)

**Comment by Rudloff** [comment]
Hello,
This is probably because the `amenity=restaurant` tag is on a [relation](https://wiki.openstreetmap.org/wiki/Relation) and restaurants should only be nodes or ways so OVM does not look for relations.

**Comment by Rudloff** [comment]
No answer so I'm closing. Feel free to reopen if you need more info.
