### ISSUE TITLE
OVM editor does not find address

### ISSUE THREAD

**Issue by janvlug** [Rudloff/openvegemap#44]
When I search for "Renbaanstraat 1,  Den Haag" in OVM, this address is not found. However, when I search for this address in OSM, it is found.

**Comment by Rudloff** [comment]
Hello,
I don't see any restaurant, bar, etc. on OSM at this address.
The editor only returns nodes that are in these categories (see https://github.com/Rudloff/openvegemap-editor/issues/3).

**Comment by Rudloff** [comment]
No answer so I'm closing. Feel free to reopen if you need more info.

**Comment by janvlug** [comment]
Sorry, I missed your request for more info. Indeed there is no restaurant. I misunderstood the search functionality. I thought it could be used for adding new restaurants, instead of searching for existing ones. So you are right in closing this issue.
