### ISSUE TITLE
[F.R.] Keep the lateral drawer behind the top panel

### ISSUE THREAD

**Issue by moshpirit** [Rudloff/openvegemap#47]
I think aesthetically fits better and there's a lot of free space in the drawer so...

**Comment by Rudloff** [comment]
Would something like this be better?
![capture d ecran - 2018-06-10 a 22 57 22](https://user-images.githubusercontent.com/840125/41206434-4c0468fa-6d04-11e8-91f1-eab8de32100d.png)

**Comment by moshpirit** [comment]
Much better!! thank you!! :+1:
