### ISSUE TITLE
Broken URL to restaurant

### ISSUE THREAD

**Issue by janvlug** [Rudloff/openvegemap#50]
The URL to Deshima (https://openvegemap.netlib.re/#zoom=19&lat=52.361438&lon=4.886523) is incorrectly prefixed with: https://openvegemap.netlib.re

See: https://www.openstreetmap.org/node/3893178572

**Comment by Rudloff** [comment]
Hello,

The URL was incorrect (it was missing the `http://` part). I fixed it on OSM.
