### ISSUE TITLE
Feature request: filter out shops

### ISSUE THREAD

**Issue by dos1** [Rudloff/openvegemap#53]
On OpenStreetMap, convenience stores and supermarkets can also be tagged with `diet:vegetarian` and `diet:vegan` tags. OpenVegeMap displays them right now, which can be a nice thing to have, but without ability to hide them it just gives you a false hope that there's something on the map there until you check it out ;)

**Comment by Rudloff** [comment]
I wanted to do this a while ago but forgot. I will remove shops in the next release.
