### ISSUE TITLE
Show address when show restaurant details

### ISSUE THREAD

**Issue by axelsimon** [Rudloff/openvegemap#57]
Hi,
currently, when touching a restaurant to get more details, you get their website and whether they do take away or not, but you don't get a very important piece of info: their actual, physical location.

I think it would make sense to put that before the phone number.

Thanks!

**Comment by dimqua** [comment]
Agreed, the phone number is useless to me in most cases.

**Comment by Rudloff** [comment]
I don't think we should remove the phone number, as it is useful to some people (to book a table, for example).

But we can certainly add the house number and street name when it is available. (The Overpass API does not always return this information, depending on how the POI is tagged.)

**Comment by AntoineJaury** [comment]
Have you thought to combine Overpass API with a Geocoding tool like Nominatim to get more complete address information? 

`addr:` tags are not often filled on OpenStreetMap and in some countries the `addr:city` is even deprecated as the city area already provides this information. Nominatim seems to do the job of finding this information for us.

I've same problematic as you for addresses on the [CartoVrac project](https://github.com/vivreanantes/cartovrac). I haven't used Nominatim yet but I'll try it in the future. I can keep you informed if you want.

**Comment by Rudloff** [comment]
I have thought about it but it would add an extra request when opening the popup. Nominatim is sometimes quite slow so I guess we would have to do this asynchronously and add the info once it is fetched.
(I would prefer if the Overpass API could just return the address in a nicer way, but I guess that is not possible.)

**Comment by AntoineJaury** [comment]
Caching data on server side could solve the problem as http requests would be done asynchronously. Once a day the Overpass API request would be done and completed with Nominatim geocoding.

The cons of that solution is that if someone contributes to the OpenVegeMap, he won't be able to see directly the result of his contribution. He will have to wait for the server cache refresh.
