### ISSUE TITLE
Consider adding description feature to restaurants

### ISSUE THREAD

**Issue by jkarlson** [Rudloff/openvegemap#58]
While it may not fit the model of storing all the data in openstreetmap, it would be a important feature to have a way to store descriptions of the restaurants somewhere, not all of them have even webpages you can link to.

**Comment by Rudloff** [comment]
Hello,
There is a description tag on OSM: https://wiki.openstreetmap.org/wiki/Key:description
I don't know if it is frequently used, but we could add support for it.

**Comment by dimqua** [comment]
Would be nice, especially if support for it can be added to OVM editor as well.

**Comment by jkarlson** [comment]
I missed that there are already https://wiki.openstreetmap.org/wiki/Key:cuisine and https://wiki.openstreetmap.org/wiki/Key:diet tags supported, just they were missing on some of the restaurants I checked. What is severely lacking is the diet tag missing support for mostly in addition to the current yes, no and only.

As these are descriptions of commercial services there were also notes forbidding the use of descriptions as ads, which might also be relevant here. Besides the clearly subjective ratings on eg. google maps or happy cow that OSM probably does not want, I guess we'll need to think what is the expressions that we can't currently do.

**Comment by Rudloff** [comment]
Yes, descriptions are for strictly objective information. That's why I'm reluctant to add it to the editor, I'm worried inexperienced contributors will add descriptions that don't fit the OSM rules. I would prefer to only add simple yes/no questions to the editor.

For subjective reviews, we are planning on integrating https://lib.reviews/: https://github.com/Rudloff/openvegemap-cordova/issues/7

**Comment by dimqua** [comment]
Is there any free (as a beer, at least) API that we can use to fetch strictly objective information? I guess, not.

**Comment by Rudloff** [comment]
I will add support for the `description` tag in OVM, but not in the editor (at least for now).
That way, if OSM contributors add descriptions for restaurants, we will display them.

**Comment by dimqua** [comment]
Nice! What are you going to display by default: English version of the description or localized version?

**Comment by Rudloff** [comment]
I'm only displaying `description=` for now, according to the OSM wiki, it should be in the local language.
