### ISSUE TITLE
OVM unable to load any data

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#59]
I can't see any restaurants at all (the same with the app from F-Droid).

![](https://i.imgur.com/sBpbwsy.png)

**Comment by Rudloff** [comment]
Hello,
I can't reproduce.
Can you open your browser console and check if there is any error?

**Comment by dimqua** [comment]
I get this:
> Content Security Policy: The page's settings blocked the loading of a resource data:image/gif;base64,R0lGODlhAQABAAD/AC… («img-src»).

**Comment by Rudloff** [comment]
Hum, that's not it, this error is unrelated.

Did you try to clear the cache of your browser?
Does this happen everywhere in the world or just when displaying a specific city?

**Comment by dimqua** [comment]
There're a few more:
>Content Security Policy: The page's settings blocked the loading of a resource at  inline («script-src»).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://overpass-api.de/api/interpreter?data=[out:json];node(48.80172338060671,2.285585403442383,48.911499416812724,2.417421340942383)[~%22^diet:.*$%22~%22.%22];out;way(48.80172338060671,2.285585403442383,48.911499416812724,2.417421340942383)[~%22^diet:.*$%22~%22.%22];out%20center;. (Reason: CORS request did not succeed).

Problably I messed up with my browser's settings (Firefox), since all works fine in Tor Browser, for example.
But I have the same problem in Android app, even previous versions.

> Does this happen everywhere in the world

Yes.

**Comment by Rudloff** [comment]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://overpass-api.de/api/interpreter?data=[out:json];node(48.80172338060671,2.285585403442383,48.911499416812724,2.417421340942383)[~%22^diet:.*$%22~%22.%22];out;way(48.80172338060671,2.285585403442383,48.911499416812724,2.417421340942383)[~%22^diet:.*$%22~%22.%22];out%20center;. (Reason: CORS request did not succeed).

This is definitely the problem. But it should not happen because this domain is authorized here: https://github.com/Rudloff/openvegemap/blob/15a892e63fff9d8b00e880d75548146d25c46064/.htaccess#L19

I will have to investigate further.
Can you please open https://mybrowser.fyi/ and click on *Copy link to this report* then paste it here?

**Comment by dimqua** [comment]
Can't do it right now, but basically: Firefox 64 on Windows with JS and first-party cookies enabled.

BTW, can Android work if the website is down? I have noticied this is the case at the moment.

**Comment by Rudloff** [comment]
Do you have a Firefox extension (like Ghostery, Privacy Badger or Adblock) that could block third-party requests?

> BTW, can Android work if the website is down? I have noticied this is the case at the moment.

Yes, the Android app contains all the code and calls the OSM API directly so it does not need my server.

**Comment by dimqua** [comment]
@Rudloff Yes, but when restart the browser with extensions disabled, the problem persists. Probably, some issue in configs leds to this error.

More interestingly though, I've found that the site doesn't work for in GNU IceCat (latest version) with all the addons disabled. And the only error is:
> Content Security Policy: The page’s settings blocked the loading of a resource at data:image/gif;base64,R0lGODlhAQABAAD/AC... (“img-src”).

**Comment by Rudloff** [comment]
I can't reproduce with Icecat 60 (it works if I disable the Searxes addon).
I really don't know what is happening here (maybe an issue with your ISP preventing you from connecting to overpass-api.de?).

**Comment by dimqua** [comment]
@Rudloff Yes! No wonder it works in Tor Browser. :-)
