### ISSUE TITLE
Shops filter

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#61]
Is it possible to do not display shops if they're not vegetarian-friendly on the map?

**Comment by hermann-san** [comment]
good point, I've checked for Berlin and I can see 4 backery shops that are in "unknown" status. 
I don't understand why they are there. Maybe someone added those as potentially veggie, but it needs to be verified at the location itself.

I believe that those shops can't be filtered in the current app version (I'm not a developer though).

**Comment by dimqua** [comment]
I've have seen a butchery shop marked as "unknown". :-D

Besides, vegetarian/vegan shops use the same marker as restaurants, IMHO it's confusing.

**Comment by Rudloff** [comment]
Unknown is when the node has a `diet:` key but not for vegan/vegetarian (probably another diet like gluten-free), it is mostly useful for people who are actively contributing and are looking for incomplete data to fix.

I think I will make the shops follow the general filters setting so if you hide non-vegetarian restaurants, it will hide non-vegetarian shops as well.

**Comment by dimqua** [comment]
@Rudloff these places are displayed on the map as unknown:
https://www.openstreetmap.org/node/5024383123
https://www.openstreetmap.org/node/3629353839
with the default filter set (non-veg restaurants aren't enabled).

**Comment by Rudloff** [comment]
https://github.com/Rudloff/openvegemap/commit/f0eb8ef21f73d7b77e1de1f0c5b032141096f8a1 is still only on the develop branch. It will be included in the next release and this will make this kind of shop only appear if the *Not vegetarian* filter is checked.
