### ISSUE TITLE
Use lib.reviews as a review backend

### ISSUE THREAD

**Issue by picsi** [Rudloff/openvegemap#65]
In order to become a true HappyCow substitute (as well as more useful), it would be great to use https://lib.reviews as a backend for checking reviews of places and writing reviews. There are already some vegan restaurants listed: https://lib.reviews/team/veg(etari)an

Pinging @eloquence

**Comment by Rudloff** [comment]
Is there a documentation for the API somewhere? I can't find a way to get the feed of reviews as JSON.

**Comment by Rudloff** [comment]
Blocked by https://github.com/eloquence/lib.reviews/issues/226.

**Comment by Rudloff** [comment]
I added a *Reviews* button (it will be in the next release).
It is just a link to the https://lib.reviews/ page of the OSM object for now. (We can expand it later by displaying reviews directly in OVM.)
