### ISSUE TITLE
Recognize ; as a separator

### ISSUE THREAD

**Issue by picsi** [Rudloff/openvegemap#69]
Currently OVM can't parse correctly a POI with more than one phone number: https://openvegemap.netlib.re/#zoom=19&lat=35.708289&lon=139.723383

The solution would be to recognize ; as a separator.

**Comment by Rudloff** [comment]
Hello,
This was fixed recently: https://github.com/Rudloff/openvegemap/commit/1b3b5820c628376a6f02d4aa300a18709c4041c7
It will be in the next release.
