### ISSUE TITLE
Can't donate trough Liberapay

### ISSUE THREAD

**Issue by forteller** [Rudloff/openvegemap#76]
Hi. Thank you for a great service!

Just wanted you to know that if you click in the Donate button in the about-box you're sent to a page where you can't donate. It just says "The user Rudloff doesn't accept donations."

https://liberapay.com/Rudloff/donate

Just FYI. Thanks again!

**Comment by Rudloff** [comment]
Hello,
I don't have a legal status allowing me to receive this kind of donations anymore, so I will remove the link.
