### ISSUE TITLE
Day shown twice in opening hours

### ISSUE THREAD

**Issue by janvlug** [Rudloff/openvegemap#82]
Monday is shown twice for Trevi's: https://openvegemap.netlib.re/#zoom=19&lat=52.350372&lon=4.89017

**Comment by Rudloff** [comment]
Thanks for the report.

The opening hours code is kind of messy and it might be a good thing to rewrite it (and maybe use some more robust code like [YoHours](https://framagit.org/PanierAvide/YoHours/-/tree/master/#integration)).

**Comment by Rudloff** [comment]
I switched to [simple-opening-hours](https://github.com/wbkd/simple-opening-hours) and this bug should be fixed in the next release.
