### ISSUE TITLE
Vending machine in /js/poi.js

### ISSUE THREAD

**Issue by KristjanESPERANTO** [Rudloff/openvegemap#88]
In the file `/js/poi.js` in the function `getAmenityIcon` is an entry for "vending_machine" which doesn't returns an emoji. Is this a mistake? I can't find a suitable emoji for vending machine.

```
        case 'vending_machine':
            return 'Vending machine';
```

**Comment by Rudloff** [comment]
See https://github.com/Rudloff/openvegemap/issues/64.
I could not find an appropriate emoji so I used text instead.

**Comment by KristjanESPERANTO** [comment]
Okay, that makes sense. Vending machines usually don't have names. So there would be nothing in the title. Even a appropriate emoji wouldn't be enough. Thanks.
