### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by rouelibre1** [Rudloff/openvegemap#91]
**Describe the bug**

Search is not working at all

**Steps to reproduce**

1. Open https://openvegemap.netlib.re/ 
2. Zoom on Strasbourg
3. Search for "Au petit artisan"

**Video**

https://www.awesomescreenshot.com/video/1919064?key=f3586642e50d74b2932ce25ea6544009

**Config**

Windows 10
Firefox 83.0

**Comment by Rudloff** [comment]
Thanks for the report!
This will be fixed in the next release.

**Comment by haansn08** [comment]
I still get the `Uncaught TypeError: this.geocoder is undefined` error on Firefox 98. If this has been fixed already it seems to have regressed.

**Comment by Rudloff** [comment]
Thanks for the reminder. I published [a new release](https://github.com/Rudloff/openvegemap/releases/tag/1.0.1) that includes the fix.
